In [1]:
import numpy as np

## Linear curve fitting

In [2]:
X = np.array(
    [
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
    ]
)

In [3]:
y = np.array([1.2, 2.3, 2.3, 3.3])

In [24]:
w_mle1 = np.linalg.inv(X.T @ X) @ X.T @ y

In [25]:
w_mle1

array([0.7 , 0.63])

In [39]:
error1 = np.sum((y - X @ w_mle1) ** 2)

In [40]:
error1

0.22300000000000011

In [8]:
# y = 1 + 1/2 * X

In [9]:
# e = [-0.3, 0.3, -0.2, 0.3]

## Polinomial curve fitting

### P = 2

In [10]:
w = [1, 0.5]
e = [-0.3, 0.3, -0.2, 0.3]

In [11]:
y = X @ w + e

In [12]:
y

array([1.2, 2.3, 2.3, 3.3])

In [13]:
# y = w0 + w1 * x + w2 * X^2 

In [14]:
PHI2 = np.array(
    [
        [1, 1, 1],
        [1, 2, 4],
        [1, 3, 9],
        [1, 4, 16],
    ]
)

In [28]:
w_mle2 = np.linalg.inv(PHI2.T @ PHI2) @ PHI2.T @ y

In [31]:
w_mle2

array([ 0.575,  0.755, -0.025])

In [ ]:
error2 = np.sum((y - PHI2 @ w_mle2) ** 2)

In [ ]:
error2

0.22050000000000003

### P = 3

In [34]:
PHI3 = np.array(
    [
        [1, 1, 1, 1],
        [1, 2, 4, 8],
        [1, 3, 9, 27],
        [1, 4, 16, 64],
    ]
)

In [41]:
w_mle3 = np.linalg.inv(PHI3.T @ PHI3) @ PHI3.T @ y

In [42]:
w_mle3

array([-3.1 ,  6.6 , -2.65,  0.35])

In [43]:
error3 = np.sum((y - PHI3 @ w_mle3) ** 2)

In [44]:
error3

1.4429011923085806e-24

In [45]:
np.isclose(error3, 0)

True